org: jlinn
app: serverless-with-aws
service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
